#include <stdio.h>
main()
{
	float peso;
	printf("Ingresa el peso en KG: ");
	scanf("%f",&peso);
	if(peso<47)
	{
		if(peso>0)
		{
			printf("\n\nPaja");
		}
		else
		{
			printf("\n\nIngrese un peso valido");
		}
	}
	else
	{
		if(peso<=49)
		{
			printf("\n\nMinimosca");
		}
		else
		{
			if(peso<=51)
			{
				printf("\n\nMosca");
			}
			else
			{
				if(peso<=52)
				{
					printf("\n\nSupermosca");
				}
				else
				{
					if(peso<=53)
					{
						printf("\n\nGallo");
					}
					else
					{
						if(peso<=55)
						{
							printf("\n\nSupergallo");
						}
						else
						{
							if(peso<=57)
							{
								printf("\n\nPluma");
							}
							else
							{
								if(peso<=59)
								{
									printf("\n\nSuperpluma");
								}
								else
								{
									if(peso<=61)
									{
										printf("\n\nLigero");
									}
									else
									{
										if(peso<=63)
										{
											printf("\n\nSuperligero");
										}
										else
										{
											if(peso<=66)
											{
												printf("\n\nWelter");
											}
											else
											{
												if(peso<=69)
												{
													printf("\n\nSuperwelter");
												}
												else
												{
													if(peso<=72)
													{
														printf("\n\nMedio");
													}
													else
													{
														if(peso<=76)
														{
															printf("\n\nSupermedio");
														}
														else
														{
															if(peso<=79)
															{
																printf("\n\nSemipesado");
															}
															else
															{
																if(peso<=86)
																{
																	printf("\n\nCrucero");
																}
																else
																{
																	printf("\n\nPesado");
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
